import type { Translations } from "./pt-BR";

export const en: Translations = {
  header: {
    resource: "Total Resource",
    resourceTooltip: "Sum of resources from all lines",
    tickets: "Tickets",
    ticketsTooltip: "Purchase Currency",
    upgrades: "Upgrades",
    upgradesTooltip: "Milestone Currency",
    level: "Level",
    levelTooltip: "Total generators in production",
    fps: "FPS",
    fpsTooltip: "Frames per second",
  },
  footer: {
    upgrades: "Upgrades",
    trades: "Trades",
    back: "Back",
  },
  settings: {
    menu: "Menu",
    general: "General",
    sounds: "Sounds",
    game: "Game",
    language: "Language",
    showFps: "Show FPS",
    showFpsDesc: "Display frames-per-second counter",
    documentation: "Documentation",
    documentationDesc: "Game rules and mechanics",
    resetSettings: "Reset Settings",
    resetSettingsDesc: "Restore all options to default",
    sfxEnabled: "Sound Effects",
    sfxEnabledDesc: "Play sounds on button clicks",
    volume: "Volume",
    resetGame: "Reset Game",
    resetGameDesc: "Erase all progress and start over",
    resetConfirmText: "Are you sure? All progress will be lost.",
    confirm: "Confirm",
    cancel: "Cancel",
  },
  buyMode: {
    ariaLabel: "Amount to buy per click",
    marco: "Milestone",
    proximo: "Next",
  },
  generator: {
    lockedTitle: "Locked generator — buy to unlock",
    clickToProduce: "Click to produce manually",
    buyToUnlock: "Buy to unlock",
    resource: "Resource",
    tickets: "Tickets",
    generator: "Generator",
    buy: "Buy",
    ready: "✓ Ready",
    holdToBuy: "Click or hold to buy in bulk",
    currentQty: "Current quantity",
    nextMilestone: "Next milestone",
    claimMilestones: (count: number, coins: string) =>
      `Click to claim ${count} milestone${count !== 1 ? "s" : ""} (◆ ${coins})`,
    buyGeneratorAria: "Buy generator",
    buyUnlockAria: "Buy generator to unlock",
  },
  generatorList: {
    claimAll: (points: string) => `Claim ${points} milestone points`,
    noPending: "No pending milestones",
  },
  offline: {
    title: "Welcome back!",
    awayFor: "You were away for",
    offlineGains: "Resources earned offline",
    resource: "Resource",
    tickets: "Tickets",
    pendingUpgrades: "Pending upgrades",
    claimAndContinue: "Claim and continue",
    continue: "Continue",
  },
  upgradesPage: {
    general: "General",
    generators: "Generators",
    tickets: "Tickets",
    maxed: "Max.",
    ticketsPerSecond: "Tickets per second",
    doubleProduction: "Double production",
    tradeForTickets: "Trade resource for +1 ▲/s",
    tradesDone: "trades done",
    halfCostAll: "Cost ÷2 (all generators)",
    doubleTradeValue: "Double ▲/s per trade",
    perTrade: "per trade",
    doubleProductionGlobal: "Double production (all generators)",
    doubleMilestoneReward: "Double ◆ per milestone",
    perGenerator: "Per generator",
    cycleTime: "Cycle time",
    productionPerCycle: "Production per cycle",
    critChance: "Crit chance",
    critEfficiency: "Crit efficiency",
    holdToBuy: "hold to buy in bulk",
    lineLockedShort: "bloq.",
    lineLockedDesc: "Unlock this line to access upgrades",
    genLockedDesc: "Unlock this generator to access upgrades",
    tradeLineLockedDesc: "Unlock this line to perform trades",
    requiresGen: (gen: number, line: number) => `Requires Generator ${gen} from Line ${line}`,
  },
  docs: {
    title: "Game Documentation",
    tabBasics: "Basics",
    tabCurrencies: "Currencies",
    tabGenerators: "Generators",
    tabUpgrades: "Upgrades",
    tabLines: "Lines",
    basicsTitle: "The Basics",
    basicsText:
      'The game has <strong>10 production lines</strong>, each with <strong>10 generators</strong>, totaling 100 generators. Each line has its own color and produces its own resource. The goal is to expand all lines by buying increasingly powerful generators. Your <strong>Level</strong> (shown in the header) is the total number of generators in production (max 100).',
    currenciesTitle: "Currencies",
    baseResourceTitle: "● Resource (per line)",
    baseResourceDesc:
      "Each production line generates its own exclusive resource (shown as ● in the line\'s color). Used to buy generators within that line and to perform trades.",
    baseResourceHow: "<strong>How to Obtain:</strong> Generated by <strong>Generator 1</strong> of each line. At the start, click the Generator 1 badge to produce manually; automatic production begins after purchasing the first unit.",
    baseResourceInit: "<strong>Total Resource (Σ):</strong> The header displays the sum of resources from all lines.",
    ticketsTitle: "▲ Tickets",
    ticketsDesc:
      "Universal currency used to buy generators across all lines. Ticket cost scales with line: <strong>Line 1 = 1 ticket</strong>, Line 2 = 2 tickets, up to Line 10 = 10 tickets per generator.",
    ticketsHow:
      "<strong>How to Obtain:</strong> Once you own at least 1 generator, you automatically generate 1 Ticket per second.",
    ticketsIncrease:
      '<strong>Increasing Gain:</strong> Resource trades for ▲/s ("Trades" menu), "Double ▲/s production (×2)" and "Double ▲/s per trade" upgrades.',
    ticketsOffline:
      "<strong>Offline:</strong> Tickets are passively generated while you are offline.",
    milestonesTitle: "◆ Milestone Currency",
    milestonesDesc:
      'Used to buy upgrades in the "Upgrades" menu. Obtained by collecting milestones from generators.',
    milestonesHow:
      '<strong>How to Obtain:</strong> When reaching factors of <code class="text-pink-300">10^x</code> of a generator (10, 100, 1k, 10k…), a milestone becomes available for collection.',
    milestonesReward:
      "<strong>Reward:</strong> Scales with generator number and milestone level. Formula: (Generator #) + (Milestone Level) - 1.",
    milestonesExample:
      "E.g.: Milestone level 3 of Generator 5 = 5 + 3 - 1 = 7 ◆.",
    generatorsTitle: "Generators",
    generatorsIntro:
      "Each production line has 10 generators. Generator 1 produces the line\'s resource. Generators 2-10 produce units of the previous generator, creating an exponential chain of growth.",
    gen1: "<strong>Generator 1:</strong> Produces the <strong>line\'s resource</strong>. Starts unlocked — click its badge to produce manually. After purchasing the first unit, production is automatic.",
    gen2to20:
      "<strong>Generators 2 to 10:</strong> Produce units of the previous generator. E.g.: Generator 3 produces Generator 2 units. To unlock the purchase of a generator, you need a certain quantity of the previous generator.",
    cycleTime:
      "<strong>Cycle Time:</strong> Each tier takes DOUBLE the time of the previous one (Gen 1 = 2s, Gen 2 = 4s… Gen 10 = ~17 min). Between lines, time also doubles (Line 2 has double Line 1\'s time). Can be reduced to 0.1s with upgrades.",
    cascadeCost:
      "<strong>Cascade Cost:</strong> Each generator costs the line\'s resource, tickets (N per unit in Line N), and units of the previous generator.",
    cascadeCostExample:
      "E.g.: Generator 3 in Line 2 requires blue resource, 2 tickets ▲, and Generator 2 units.",
    upgradesTitle: "Upgrades",
    upgradesIntro:
      'The "Upgrades" menu uses ◆ to accelerate your progression. Split into 3 tabs:',
    upgCycleTitle: "Reduce Cycle Time",
    upgCycleDesc:
      "Per-generator. Cuts cycle time in half (÷2). Cost: 1, 2, 4, 8… ◆. Limit: 0.1s per cycle.",
    upgProdTitle: "Double Production",
    upgProdDesc:
      "Per-generator. Doubles output per cycle (×2). Cost: 1, 2, 4, 8… ◆. Infinite ranks.",
    upgCritChanceTitle: "Crit Chance",
    upgCritChanceDesc:
      "Per-generator. Each rank adds 2.5% crit chance (max 100% at 40 ranks). Cost: 1, 2, 4, 8… ◆.",
    upgCritMultTitle: "Crit Efficiency",
    upgCritMultDesc:
      "Per-generator. Increases crit damage multiplier (×2, ×4, ×6…). Cost: 1, 2, 4, 8… ◆. Infinite ranks.",
    upgTicketMultTitle: "Double ▲/s production (×2)",
    upgTicketMultDesc:
      "Global. Doubles all ticket generation per second. Cost: 1, 4, 16, 64… ◆ (quadruples each rank). Infinite ranks.",
    upgTradeDoublerTitle: "Double ▲/s per trade",
    upgTradeDoublerDesc:
      "Global. Doubles the ▲/s value each trade grants (1→2→4→8…). Cost: 1, 2, 4, 8… ◆.",
    upgHalfCostTitle: "Cost ÷2 (all generators)",
    upgHalfCostDesc:
      "Global. Halves resource cost and previous generator cost. Cost: 1, 2, 4, 8… ◆.",
    upgMilestoneDoublerTitle: "Double ◆ per milestone",
    upgMilestoneDoublerDesc:
      "Global. Doubles ◆ reward from collecting milestones. Cost: 2, 8, 32, 128… ◆ (quadruples each rank).",
    upgTradeTitle: "Trades (Trades menu)",
    upgTradeDesc:
      "10 independent trades, one per line. Sacrifice line resource for a permanent ▲/s gain. Cost increases per trade (500, 5k, 5M, 5B…). Does not consume ◆.",
    linesTitle: "Production Lines",
    linesIntro:
      "The game has <strong>10 production lines</strong>, each with its own <strong>color</strong>, <strong>exclusive resource</strong> and unique characteristics. Higher lines are slower but much more productive per cycle.",
    linesScaling: "Scaling between lines",
    linesScalingCycle: "Cycle time",
    linesScalingCycleDesc: "Each subsequent line has <strong>double</strong> the cycle time. Line 1 starts at 2s for Gen 1, Line 2 at 4s, Line 10 at ~17 min.",
    linesScalingProd: "Production per cycle",
    linesScalingProdDesc: "Each subsequent line produces <strong>triple</strong> per cycle. Line 1 produces 3/cycle for Gen 1, Line 2 produces 9, Line 10 produces 59,049.",
    linesScalingTickets: "Ticket cost",
    linesScalingTicketsDesc: "Line N consumes <strong>N tickets</strong> per generator purchased. Line 1 = 1▲, Line 5 = 5▲, Line 10 = 10▲.",
    linesScalingResource: "Exclusive resource",
    linesScalingResourceDesc: "Each line produces and consumes its own resource. Red line generators use red resource, blue line generators use blue resource, and so on.",
    linesUnlockTitle: "Unlocking lines",
    linesUnlock: "<strong>Line 1</strong> starts unlocked. To unlock <strong>Line N</strong>, you need at least <strong>1 unit of Generator N from Line N-1</strong>.",
    linesUnlockExample: "E.g.: To unlock Line 3, you need 1 Generator 3 from Line 2. To unlock Line 6, you need 1 Generator 6 from Line 5.",
    lineNames: [
      "Red", "Blue", "Green", "Amber", "Violet",
      "Cyan", "Orange", "Pink", "Indigo", "Lime",
    ] as unknown as string,
    lineLabel: "Line",
    lineTickets: "tickets/generator",
    lineCycleGen1: "Cycle Gen 1",
    lineProdGen1: "Prod. Gen 1",
    offlineTitle: "Offline Simulation",
    offlineText:
      "The game calculates your progress while the tab was closed, simulating all production layers and accumulating resources, tickets, and milestones across all active lines.",
  },
} as const;
